# Generated by Django 3.2.24 on 2024-02-27 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
