# Generated by Django 5.0.2 on 2024-03-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_blog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
