# Generated by Django 3.2.24 on 2024-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_slug'),
        ('blog', '0010_alter_blog_slug'),
    ]

    operations = [
    ]
