# Generated by Django 3.2.24 on 2024-03-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20240301_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='reset_token_expiry',
        ),
    ]
