# Generated by Django 5.0.3 on 2024-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='profile_images'),
        ),
    ]
